server:
  port: 0
spring:
  application:
    name: app-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 2s
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}   
